name: record_workspace

environment:
  sdk: ^3.5.0

publish_to: none

dev_dependencies:
  melos: ^7.0.0

workspace:
  - record
  - record/example
  - record_android
  - record_ios
  - record_macos
  - record_linux
  - record_platform_interface
  - record_web
  - record_windows

melos:
  # Don't generate intellij files
  ide:
    intellij: false

  command:
    # When a dependency in a package is listed it will be replaced with the following versions.
    bootstrap:
      environment:
        sdk: ^3.5.0
        flutter: ">=3.24.0"
      dev_dependencies:
        # Linter rules (https://pub.dev/packages/flutter_lints)
        flutter_lints: ^6.0.0

  clean:
    hooks:
      # Runs "flutter clean" in all Flutter packages (`--flutter`) with concurrency
      post: melos exec --flutter -c 1 -- "flutter clean"