name: record_windows
description: Windows specific implementation for record package called by record_platform_interface.
version: 1.0.3
homepage: https://github.com/llfbandit/record/tree/master/record_windows

environment:
  sdk: ^3.3.0
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  record_platform_interface: ^1.0.2

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  plugin:
    implements: record
    platforms:
      windows:
        pluginClass: RecordWindowsPluginCApi
