name: record_windows
description: Windows specific implementation for record package called by record_platform_interface.
version: 0.7.1
homepage: https://github.com/llfbandit/record/tree/master/record_windows

environment:
  sdk: ">=2.15.1"
  flutter: ">=2.8.1"

dependencies:
  flutter:
    sdk: flutter

  record_platform_interface: ^0.5.0
  path: ^1.8.0

dependency_overrides:
  record_platform_interface:
    path: ../record_platform_interface

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  plugin:
    implements: record
    platforms:
      windows:
        pluginClass: RecordWindowsPluginCApi
        dartPluginClass: RecordWindows
