name: record_ios
description: iOS implementation for record package called by record_platform_interface.
version: 1.0.0
homepage: https://github.com/llfbandit/record/tree/master/record_ios

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  record_platform_interface: ^1.2.0

flutter:
  plugin:
    implements: record
    platforms:
      ios:
        pluginClass: RecordIosPlugin
