name: record_example
description: Demonstrates how to use the record plugin.
version: 1.0.0

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.1 <3.0.0"
  flutter: ">=2.0.2"

dependencies:
  path_provider: ^2.0.1
  just_audio: ^0.7.1

  flutter:
    sdk: flutter

  record:
    path: ../


# The following section is specific to Flutter.
flutter:
  uses-material-design: true
