name: record_example
description: Demonstrates how to use the record plugin.
version: 1.0.0

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

resolution: workspace

dependencies:
  path: ^1.8.0
  path_provider: ^2.0.1
  audioplayers: ^6.5.0
  web: ^1.0.0

  flutter:
    sdk: flutter

  record: ^6.1.0

dev_dependencies:
  flutter_lints: ^6.0.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
