name: record
description: Audio recorder from microphone to a given file path with multiple codecs, bit rate and sampling rate options.
version: 2.1.1
homepage: https://github.com/llfbandit/record/record

environment:
  sdk: ">=2.12.1 <3.0.0"
  flutter: ">=2.0.2"

dependencies:
  flutter:
    sdk: flutter
  record_platform_interface: #^0.1.0
    path: ../record_platform_interface
  record_web: #^0.1.0
    path: ../record_web

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.llfbandit.record
        pluginClass: RecordPlugin
      ios:
        pluginClass: RecordPlugin
      web:
        default_package: record_web
