name: record
description: Audio recorder from microphone to file or stream with multiple codecs, bit rate and sampling rate options.
version: 5.2.1
homepage: https://github.com/llfbandit/record/tree/master/record

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/uuid
  uuid: ">=3.0.7 <5.0.0"

  record_platform_interface: ^1.2.0
  record_web: ^1.1.5
  record_windows: ^1.0.5
  record_linux: ^1.0.0
  record_android: ^1.3.1
  record_ios: ^1.0.0
  record_macos: ^1.0.0

dev_dependencies:
  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^5.0.0

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        default_package: record_android
      ios:
        default_package: record_ios
      web:
        default_package: record_web
      windows:
        default_package: record_windows
      macos:
        default_package: record_macos
      linux:
        default_package: record_linux
