name: record_linux
description: Linux specific implementation for record package called by record_platform_interface.
version: 0.3.4
homepage: https://github.com/llfbandit/record/tree/master/record_linux

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.8.1"

dependencies:
  flutter:
    sdk: flutter

  record_platform_interface: ^0.5.0
  path: ^1.8.0

# dependency_overrides:
#   record_platform_interface:
#     path: ../record_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:
  plugin:
    implements: record
    platforms:
      linux:
        pluginClass: RecordLinuxPlugin
        dartPluginClass: RecordLinux
