name: record_linux
description: Linux specific implementation for record package called by record_platform_interface.
version: 1.0.0
homepage: https://github.com/llfbandit/record/tree/master/record_linux

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  record_platform_interface: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# The following section is specific to Flutter.
flutter:
  plugin:
    implements: record
    platforms:
      linux:
        pluginClass: RecordLinuxPlugin
        dartPluginClass: RecordLinux
